# conda env create -f environment.yml
name: ecopro
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.6
  - xarray
  - matplotlib
  - cartopy
  - numpy
  - requests
  - pandas
  - netcdf4
  - rioxarray
  - rasterio
  - dask
  - zarr
  - tqdm
  - h5netcdf
  - dask-jobqueue
  - fiona
  - scikit-learn
  - geopandas
  - ray-default
  - snakemake
  - cdsapi
  - skops
  - werkzeug
