features:
 - northings
 - eastings

 - PR1-1
 - PR1-2
 - PR1-3
 - PR1-4
 - PR1-5
 - PR1-6
 - PR2-1
 - PR2-2
 - PR2-3
 - PR2-4
 - PR2-5
 - PR2-6
 - PR3-1
 - PR3-2
 - PR3-3
 - PR3-4
 - PR3-5
 - PR3-6
 - PR4-1
 - PR4-2
 - PR4-3
 - PR4-4
 - PR4-5
 - PR4-6
 - PR5-1
 - PR5-2
 - PR5-3
 - PR5-4
 - PR5-5
 - PR5-6
 - PR6-1
 - PR6-2
 - PR6-3
 - PR6-4
 - PR6-5
 - PR6-6
 - PRET1-1
 - PRET1-2
 - PRET1-3
 - PRET1-4
 - PRET1-5
 - PRET1-6
 - PRET2-1
 - PRET2-2
 - PRET2-3
 - PRET2-4
 - PRET2-5
 - PRET2-6
 - PRET3-1
 - PRET3-2
 - PRET3-3
 - PRET3-4
 - PRET3-5
 - PRET3-6
 - PRET4-1
 - PRET4-2
 - PRET4-3
 - PRET4-4
 - PRET4-5
 - PRET4-6
 - PRET5-1
 - PRET5-2
 - PRET5-3
 - PRET5-4
 - PRET5-5
 - PRET5-6
 - PRET6-1
 - PRET6-2
 - PRET6-3
 - PRET6-4
 - PRET6-5
 - PRET6-6
 - SPI1-1
 - SPI1-2
 - SPI1-3
 - SPI1-4
 - SPI1-5
 - SPI1-6
 - SPI2-1
 - SPI2-2
 - SPI2-3
 - SPI2-4
 - SPI2-5
 - SPI2-6
 - SPI3-1
 - SPI3-2
 - SPI3-3
 - SPI3-4
 - SPI3-5
 - SPI3-6
 - SPI4-1
 - SPI4-2
 - SPI4-3
 - SPI4-4
 - SPI4-5
 - SPI4-6
 - SPI5-1
 - SPI5-2
 - SPI5-3
 - SPI5-4
 - SPI5-5
 - SPI5-6
 - SPI6-1
 - SPI6-2
 - SPI6-3
 - SPI6-4
 - SPI6-5
 - SPI6-6
 - SPEI1-1
 - SPEI1-2
 - SPEI1-3
 - SPEI1-4
 - SPEI1-5
 - SPEI1-6
 - SPEI2-1
 - SPEI2-2
 - SPEI2-3
 - SPEI2-4
 - SPEI2-5
 - SPEI2-6
 - SPEI3-1
 - SPEI3-2
 - SPEI3-3
 - SPEI3-4
 - SPEI3-5
 - SPEI3-6
 - SPEI4-1
 - SPEI4-2
 - SPEI4-3
 - SPEI4-4
 - SPEI4-5
 - SPEI4-6
 - SPEI5-1
 - SPEI5-2
 - SPEI5-3
 - SPEI5-4
 - SPEI5-5
 - SPEI5-6
 - SPEI6-1
 - SPEI6-2
 - SPEI6-3
 - SPEI6-4
 - SPEI6-5
 - SPEI6-6

 - elevation
 - northness
 - slope
 - rie
 - sapa
 - sdmv
 - tpi
 - vrm

target: severity_code
