
# Directory Structure

root_dir: '/Volumes/Earth02/ecopro'
projections_subdir: 'projections/BCM'

# Script Configuration Files

bcm_config: 'config/bcm_v8.json'

# Climate Projections

projection_scenarios:
    #- HST
    - RCP45
    - RCP85

projection_models:
    #- ACCESS1-0
    #- CCSM4
    #- CESM1-BGC
    #- CMCC-CMS
    #- CNRM-CM5
    - CanESM2
    - GFDL-CM3
    #- HadGEM2-ES
