
# Directory Structure

root_dir: '/Volumes/Earth02/ecopro'
projections_subdir: 'projections/BCM'
mortality_subdir: 'tree_mortality'
bcm_raw_subdir: 'BCMv8_zip'

# Script Configuration Files

bcm_config: 'config/bcm_v8.json'
agg_config: 'config/bcm_v8_aggregation.json'
bcm_ind_config: 'config/bcm_v8_indices.json'
mort_config: 'config/tree_mortality.json'
mort_fold_config: 'config/tree_mortality_folds.json'
mort_rand_fold_config: 'config/tree_mortality_rand_folds.json'
mort_trainset_config: 'config/training_features.json'

bcm_variables:
    - aet
    - cwd
    - pck
    - pet
    - ppt
    - rch
    - run
    - str
    - tmn
    - tmx

# Climate Projections

projection_scenarios:
    #- HST
    - RCP45
    - RCP85

projection_models:
    - ACCESS1-0
    - CCSM4
    - CESM1-BGC
    - CMCC-CMS
    - CNRM-CM5
    - CanESM2
    - GFDL-CM3
    - HadGEM2-ES
