features:
  climate:
    PR:
      cumulative: 6
      back: 6
    PRET:
      cumulative: 6
      back: 6
    SPI:
      cumulative: 6
      back: 6
    SPEI:
      cumulative: 6
      back: 6

  topography:
    - elevation
    - adjsd
    - northness
    - slope
    - rie
    - sapa
    - sdmv
    - tpi
    - vrm

  heat:
    fraction_hot_days:
      back: 6

target: severity_code

years:
 - 2012
 - 2013
 - 2014
 - 2015
 - 2016
 - 2017
 - 2018
 - 2019
 - 2021

chunks:
  sample: -1
